[[community]]
== Nexus Community

=== Introduction

Sonatype Nexus OSS and Sonatype Nexus Pro are widely used in a large
variety of organizations for numerous different use cases.

Integrating Nexus and expanding its features is encouraged and enabled
by the availability of Nexus OSS under the Eclipse Public License,
<<confignx-sect-plugins, the REST API>> of Nexus and <<plugdev, the
support for plugins>> as part of Nexus itself, including writing your
own plugins.

A number of tools are available to facilitate the community of Nexus
users.

TheNexus:: A community website with numerous resources including blog
posts, videos, announcements and many others available at http://nexus.sonatype.org[http://nexus.sonatype.org].

Mailing Lists:: A number of mailing lists are available for the Nexus community:

Nexus Users::: General discussion and support for anyone using and
developing with Nexus - 
link:https://groups.google.com/a/glists.sonatype.com/forum/#!forum/nexus-users[Browse
or Subscribe].

Chat:: Sonatype provides
https://links.sonatype.com/products/nexus/community-chat[a live chat
channel] to connect to other users and developers as well as Sonatype
support and development staff.


Source Code:: The Nexus OSS codebase is a great reference for your
development of custom integrations and plugins. It is available on
GitHub at
https://github.com/sonatype/nexus-oss[https://github.com/sonatype/nexus-oss].


[[community-projects]]
=== Community Projects Overview

Nexus community projects range from open source efforts run by
Sonatype, projects run by Nexus Pro customers or Nexus OSS users to
one man, one-off hacks for some older version of Nexus.

When using any of these projects, ensure you keep the quality of the
project and their impacts on your production Nexus instance in
mind.

=== Nexus Plugins

Nexus plugins expand functionality of Nexus itself in various aspects
on the user interface and underlying features:

Nexus OSS Plugins https://github.com/sonatype/nexus-oss/tree/master/plugins[https://github.com/sonatype/nexus-oss/tree/master/plugins]::
Large number of plugins bundled with Nexus OSS including YUM
support, P2 support and others.

Example Plugins https://github.com/sonatype/nexus-example-plugins[https://github.com/sonatype/nexus-example-plugins]::
Example plugins from Sonatype.

APT Plugin https://github.com/Tangresh/nexus-apt-plugin[https://github.com/Tangresh/nexus-apt-plugin]::
APT/DEB repository support for Nexus.

Rundeck Plugin https://github.com/rundeck/nexus-rundeck-plugin[https://github.com/rundeck/nexus-rundeck-plugin]::
Nexus integration with http://rundeck.org/[Rundeck]

Webhook Plugin https://github.com/vbehar/nexus-webhook-plugin[https://github.com/vbehar/nexus-webhook-plugin]::
Support for webhook notifications for component deployments to Nexus.

Artifact Usage Plugin https://github.com/saleemshafi/nexus-artifact-usage-plugin[https://github.com/saleemshafi/nexus-artifact-usage-plugin]::
Plugin to display components depending on a specific component.

Dependency Mgt. Plugin https://github.com/Terracotta-OSS/nexus-dependency-management-plugin[https://github.com/Terracotta-OSS/nexus-dependency-management-plugin]::
Plugin to display the dependency tree of a component with further
detailed information.

GroupId Mgt. Plugin https://github.com/UW-Madison-DoIT/nexus-groupid-management-plugin[https://github.com/UW-Madison-DoIT/nexus-groupid-management-plugin]::
Plugin to help with provisioning security per groupId.

Repository Cleanup Plugin https://github.com/Vlatombe/nexus-repository-cleanup-plugin/[https://github.com/Vlatombe/nexus-repository-cleanup-plugin/]::
Scheduled task that can remove components based on age and a regular
expression pattern.

Gitlab Token Auth Plugin https://github.com/jdamick/nexus-gitlab-token-auth-plugin[https://github.com/jdamick/nexus-gitlab-token-auth-plugin]::
Nexus authentication support using http://gitlab.org/[Gitlab] user
token.

AWS S3 Publish Plugin https://github.com/carrot-garden/carrot-nexus[https://github.com/carrot-garden/carrot-nexus]::
Nexus plugin to publish components deployed to Nexus also to AWS S3.

Hipchat for Nexus Plugin https://bitbucket.org/tpettersen/hipchat-for-nexus[https://bitbucket.org/tpettersen/hipchat-for-nexus]::
Supports notifications in HipChat when components matching a pattern 
are deployed to Nexus.

=== Nexus Integrations

Nexus Maven Plugins https://github.com/sonatype/nexus-maven-plugins[https://github.com/sonatype/nexus-maven-plugins]::
The official Nexus Staging Maven Plugin and the Nexus
M2Settings Maven Plugin from Sonatype. The plugins are using the Nexus
REST API client library and can
be used as example for your own Maven plugins or other Java based clients.

Nexus Ant Tasks https://github.com/sonatype/nexus-ant-tasks[https://github.com/sonatype/nexus-ant-tasks]::
The official Nexus Staging Ant Tasks from Sonatype.

Puppet Module for Nexus https://github.com/hubspotdevops/puppet-nexus[https://github.com/hubspotdevops/puppet-nexus]::
Puppet module to install and configure Nexus, authored by HubSpot

Puppet Module for Nexus https://forge.puppetlabs.com/atlassian/nexus_rest[https://forge.puppetlabs.com/atlassian/nexus_rest]::
Another Puppet module to manage Nexus, authored by Atlassian

Nexus Cookbook https://github.com/RiotGames/nexus-cookbook[https://github.com/RiotGames/nexus-cookbook]::
 Chef cookbook to install and configure Nexus.

Openshift Nexus https://github.com/hongun/openshift-nexus[https://github.com/hongun/openshift-nexus]::
Scripts to provision Nexus on https://www.openshift.com/[OpenShift].

Nexus CLI https://github.com/RiotGames/nexus_cli[https://github.com/RiotGames/nexus_cli]::
Set of command line programs to interact with Nexus.

Nexus RPM Package https://github.com/jbraeuer/nexus-oss-rpms[https://github.com/jbraeuer/nexus-oss-rpms]::
Nexus as RPM package.

Nexus DEB Package https://github.com/tobrien/nexus-oss-deb[https://github.com/tobrien/nexus-oss-deb]::
Nexus as DEB package.

Puppet Nexus Client https://github.com/cescoffier/puppet-nexus[https://github.com/cescoffier/puppet-nexus]::
Puppet module to retrieve components from Nexus.

Gradle Plugin https://github.com/bmuschko/gradle-nexus-plugin[https://github.com/bmuschko/gradle-nexus-plugin]::
Gradle plugin to deploy components to Nexus and via OSSRH to the Central Repository.

Gradle Staging Plugin https://github.com/adaptivecomputing/plugins-gradle/tree/master/nexus-workflow[https://github.com/adaptivecomputing/plugins-gradle/tree/master/nexus-workflow]::
Gradle plugin to deploy components to Nexus and via OSSRH to the Central 
Repository with good support for staging automation.

SBT Plugin https://github.com/xerial/sbt-sonatype[https://github.com/xerial/sbt-sonatype]::
Gradle plugin to deploy components to Nexus and via OSSRH to the
Central Repository.

List Versions Jenkins Plugin https://github.com/USGS-CIDA/list-nexus-versions-plugin[https://github.com/USGS-CIDA/list-nexus-versions-plugin]::
Jenkins plugin to display component versions available in Nexus.

Nexus Metadata Jenkins Plugin https://github.com/marcelbirkner/nexus-metadata-plugin[https://github.com/marcelbirkner/nexus-metadata-plugin]::
Jenkins plugin to add custom metadata with deployments to Nexus Pro.

Artifact Promotion Jenkins Plugin https://github.com/jenkinsci/artifact-promotion-plugin[https://github.com/jenkinsci/artifact-promotion-plugin]::
Jenkins plugin allowing you to promote components to different repositories in Nexus OSS

Go Maven Poller https://github.com/ThoughtWorksInc/go-maven-poller[https://github.com/ThoughtWorksInc/go-maven-poller]::
Package material plugin for
http://www.thoughtworks.com/products/go-continuous-delivery[Go] that can poll Nexus for components.

Nexus Docker Image https://registry.hub.docker.com/u/conceptnotfound/sonatype-nexus/[https://registry.hub.docker.com/u/conceptnotfound/sonatype-nexus/]::
simple Docker image with Nexus

Nexus NPM Docker Image https://github.com/marcellodesales/nexus-npm-registry-docker-image[https://github.com/marcellodesales/nexus-npm-registry-docker-image]::
Docker Image of Nexus with NPM support preconfigured

=== Other Community Projects

Nexus Performance Testing Library https://github.com/sonatype/nexus-perf[https://github.com/sonatype/nexus-perf]::
Regression and stress test library for Nexus from Sonatype.

Repository Management With Nexus https://github.com/sonatype/nexus-book[https://github.com/sonatype/nexus-book]::
The source code for the book, which is the official documentation for
Nexus OSS and Nexus Pro.

Nexus Book Examples https://github.com/sonatype/nexus-book-examples[https://github.com/sonatype/nexus-book-examples]::
Examples for the Nexus trial guide chapter of the book 'Repository
Management with Nexus'.

Nexus Introduction https://github.com/sonatype/nexus-introduction-presentation[https://github.com/sonatype/nexus-introduction-presentation]::
Slides and examples to present about Sonatype Nexus at user groups or in similar settings.


=== Contributing

All of the projects listed in <<community-projects>> are community
efforts and open to your participation. If you are aware of any other
projects or would like to have your project listed here, please
contact us at mailto:books@sonatype.com[books@sonatype.com].


