[[community]]
== Nexus Community

Sonatype Nexus Open Source as well Sonatype Nexus Professional are
widely used and adapted to the varied circumstances and
requirements at open source projects and organizations and small to
very large enterprises.

Integrating Nexus and expanding its features is encouraged and enabled
by the availability of Nexus Open Source under the Eclipse Public
License, <<confignx-sect-plugins, the REST API>> of Nexus and
<<plugdev, the support for plugins>> as part of Nexus itself including
writing your own plugins.

A number of tools are available to facilitate the community of Nexus
users.

.Mailing Lists

A number of mailing lists are available for the Nexus community:

Nexus Users:: General discussion and support for anyone using Nexus - 
mailto:nexus-user-subscribe@sonatype.org[Subscribe] or
http://maven.40175.n5.nabble.com/Nexus-Maven-Repository-Manager-f127898.html[Browse
the Archive]

Nexus Developers:: General discussion and support for anyone who wants
to get involved in the development of Nexus - mailto:nexus-dev-subscribe@sonatype.org[Subscribe] or
http://maven.40175.n5.nabble.com/Nexus-Maven-Repository-Manager-Dev-List-f132371.html[Browse
the Archive]

Nexus Professional Users:: General discussion and support for
professional Nexus users - mailto:nexus-pro-users-subscribe@sonatype.org[Subscribe]

.Chat

Sonatype provides
https://links.sonatype.com/products/nexus/community-chat[a live chat
channel] to connect to other users and developers as well as Sonatype
support and development staff.


.Source Code

The Nexus Open Source codebase is a great reference for your
development of custom integrations and plugins. It is available on
GitHub at
https://github.com/sonatype/nexus-oss[https://github.com/sonatype/nexus-oss].


[[community-projects]]
=== Community Projects

Nexus community projects range from open source efforts run by
Sonatype, projects run by Nexus Professional customers or Nexus Open
Source users to one man, one off hacks for some older version of
Nexus.

When using any of these projects, ensure you keep the quality of the
project and their impact on your production Nexus instance in
mind.

==== Nexus Plugins

Nexus plugins expand functionality of Nexus itself in various aspects
on the user interface and underlying features:

Nexus Open Source Plugins https://github.com/sonatype/nexus-oss/tree/master/plugins[https://github.com/sonatype/nexus-oss/tree/master/plugins]::
Large number of plugins bundled with Nexus Open Source including YUM
support, P2 support and others

Example Plugins https://github.com/sonatype/nexus-example-plugins[https://github.com/sonatype/nexus-example-plugins]::
Example plugins from Sonatype

Ruby Support https://github.com/sonatype/nexus-ruby-support[https://github.com/sonatype/nexus-ruby-support]::
Components from Sonatype to enable RubyGems support in Nexus

APT Plugin https://github.com/Tangresh/nexus-apt-plugin[https://github.com/Tangresh/nexus-apt-plugin]::
APT/DEB repository support for Nexus

Rundeck Plugin https://github.com/vbehar/nexus-rundeck-plugin[https://github.com/vbehar/nexus-rundeck-plugin]::
Nexus integration with http://rundeck.org/[Rundeck]

Webhook Plugin https://github.com/vbehar/nexus-webhook-plugin[https://github.com/vbehar/nexus-webhook-plugin]::
support for webhook notifications for component deployments to Nexus

Artifact Usage Plugin https://github.com/saleemshafi/nexus-artifact-usage-plugin[https://github.com/saleemshafi/nexus-artifact-usage-plugin]::
Plugin to display components depending on a specific component

Dependency Mgt Plug.in https://github.com/Terracotta-OSS/nexus-dependency-management-plugin[https://github.com/Terracotta-OSS/nexus-dependency-management-plugin]::
Plugin to display the dependency tree of a component with further
detailed information

GroupId Mgt. Plugin https://github.com/UW-Madison-DoIT/nexus-groupid-management-plugin[https://github.com/UW-Madison-DoIT/nexus-groupid-management-plugin]::
Plugin to help with provisioning security per groupId

Repository Cleanup Plugin https://github.com/Vlatombe/nexus-repository-cleanup-plugin/[https://github.com/Vlatombe/nexus-repository-cleanup-plugin/]::
scheduled task that can remove components based on age and a regular
expression pattern

Gitlab Token Auth Plugin https://github.com/jdamick/nexus-gitlab-token-auth-plugin[https://github.com/jdamick/nexus-gitlab-token-auth-plugin]::
Nexus authentication support using http://gitlab.org/[Gitlab] user
token

AWS S3 Publish Plugin https://github.com/carrot-garden/carrot-nexus[https://github.com/carrot-garden/carrot-nexus]::
Nexus plugin to publish components deployed to Nexus also to AWS S3

NPM Repository Plugin https://github.com/georgy/nexus-npm-repository-plugin[https://github.com/georgy/nexus-npm-repository-plugin]::
Nexus plugin providing support for the Javascript based Node Packaged
Modules NPM system.

==== Nexus Integrations

Nexus Maven Plugins https://github.com/sonatype/nexus-maven-plugins[https://github.com/sonatype/nexus-maven-plugins]::
The official Nexus Staging Maven Plugin and the Nexus
M2Settings Maven Plugin from Sonatype. The plugins are using the Nexus
REST API client library and can
be used as example for your own Maven plugins or other Java based clients.

Nexus Ant Tasks https://github.com/sonatype/nexus-ant-tasks[https://github.com/sonatype/nexus-ant-tasks]::
The official Nexus Staging Ant Tasks from Sonatype.

Puppet Nexus https://github.com/hubspotdevops/puppet-nexus[https://github.com/hubspotdevops/puppet-nexus]::
Puppet module to install and configure Nexus

Nexus Cookbook https://github.com/RiotGames/nexus-cookbook[https://github.com/RiotGames/nexus-cookbook]::
 Chef cookbook to install and configure Nexus

Openshift Nexus https://github.com/hongun/openshift-nexus[https://github.com/hongun/openshift-nexus]::
Scripts to provision Nexus on https://www.openshift.com/[OpenShift

Nexus CLI https://github.com/RiotGames/nexus_cli[https://github.com/RiotGames/nexus_cli]::
Set of command line programs to interact with Nexus

Nexus RPM Package https://github.com/jbraeuer/nexus-oss-rpms[https://github.com/jbraeuer/nexus-oss-rpms]::
Nexus as RPM package

Nexus DEB Package https://github.com/tobrien/nexus-oss-deb[https://github.com/tobrien/nexus-oss-deb]::
Nexus as DEB package

Puppet Nexus Client https://github.com/cescoffier/puppet-nexus[https://github.com/cescoffier/puppet-nexus]::
Puppet module to retrieve components from Nexus

Gradle Plugin https://github.com/bmuschko/gradle-nexus-plugin[https://github.com/bmuschko/gradle-nexus-plugin]::
Gradle plugin to deploy components to Nexus and via OSSRH to the Central Repository

Gradle Staging Plugin https://github.com/adaptivecomputing/plugins-gradle/tree/master/nexus-workflow[https://github.com/adaptivecomputing/plugins-gradle/tree/master/nexus-workflow]::
Gradle plugin to deploy components to Nexus and via OSSRH to the Central Repository with good support for staging automation

SBT Plugin https://github.com/xerial/sbt-sonatype[https://github.com/xerial/sbt-sonatype]::
Gradle plugin to deploy components to Nexus and via OSSRH to the
Central Repository

List Versions Jenkins Plugin https://github.com/USGS-CIDA/list-nexus-versions-plugin[https://github.com/USGS-CIDA/list-nexus-versions-plugin]::
Jenkins plugin to display component versions available in Nexus

Nexus Metadata Jenkins Plugin https://github.com/marcelbirkner/nexus-metadata-plugin[https://github.com/marcelbirkner/nexus-metadata-plugin]::
jenksing plugin to add custom metadata with deployments to Nexus Professional

Go Maven Poller https://github.com/ThoughtWorksInc/go-maven-poller[https://github.com/ThoughtWorksInc/go-maven-poller]::
Package material plugin for
http://www.thoughtworks.com/products/go-continuous-delivery[Go] that
can poll Nexus for components

Hipchat for Nexus Plugin https://bitbucket.org/tpettersen/hipchat-for-nexus[https://bitbucket.org/tpettersen/hipchat-for-nexus]::
Supports notifications in HipChat when components matching a pattern
are deployed to Nexus

==== Other Projects

Nexus Performance Testing Library https://github.com/sonatype/nexus-perf[https://github.com/sonatype/nexus-perf]::
regression and stress test library for Nexus from Sonatype

Repository Management With Nexus https://github.com/sonatype/nexus-book[https://github.com/sonatype/nexus-book]::
the source code for the book, which is the official documentation for
Nexus Open Source and Nexus Professional

Nexus Book Examples https://github.com/sonatype/nexus-book-examples[https://github.com/sonatype/nexus-book-examples]::
examples for the Nexus trial guide chapter of the book 'Repository
Management with Nexus'

Nexus Introduction https://github.com/sonatype/nexus-introduction-presentation[https://github.com/sonatype/nexus-introduction-presentation]::
slides and examples to present about Sonatype Nexus at user groups or in similar settings



.Contributing

All of the projects listed in <<community-projects>> are community
efforts and open to your participation. If you are aware of any other
projects or would like to have your project listed here, please
contact us at mailto:books@sonatype.com[books@sonatype.com].


