[[contrib]]
[appendix]
== Contributing to the Nexus Book

This appendix covers the basics of contributing to the book you are
currently reading. This book is an open source project, you can
participate in the writing effort if you have an idea for
documentation. Sonatype's books are
different: they are open writing efforts and we see documentation
contributions as having equal value to code contributions.  If you are
interested in our technology, we'd welcome your contribution.

[[contrib-sect-cla]]
=== Contributor License Agreement (CLA)

In order to contribute to the Nexus book, you will first need to fill
out a contributor license agreement. This is a legal agreement between
you and Sonatype which ensures that your contributions are not covered
by any other legal requirements. Sonatype requires contributors to
sign this agreement for all major contributions which are larger than
a single section. If your contribution consists of finding and fixing
simple typos or suggesting minor changes to the wording or sequence of
a particular section, you can contribute these changes via the
Sonatype JIRA instance.  If you contribution involves direct
contribution of a number of sections or chapters you will first need
to sign our Contributor License Agreement (CLA).

To download the CLA from the following URL:
http://www.sonatype.org/SonatypeCLA.pdf

Once you have completed and signed this document, you can email the
scan to mailto:books@sonatype.com[books@sonatype.com].

=== How to Contribute

The source code for the book is hosted on GitHub in the
https://github.com/sonatype/nexus-book[nexus-book]
project. Instructions on tools used to author content as well as
building the book and more can be found there.

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////
