[[backup]]
==  Backing Up and Restoring {nxrm}
{inall}

TBD

[[backup-introduction]]
=== Introduction

TBD

[[why-backup]]
=== Why Backup?

TBD

[[backup-configuration]]
=== Backup Plan

TBD
////
Checklist, self-repair tasks - TBD
////


[[backup-requirements]]
=== Requirements for Backing Up {nxrm}

TBD


[[backup-preparation]]
=== Preparing a Backup for {nxrm}

TBD
////
Formalize: Before you execute a backup of your OrientDB, select a backup tool of your preference to
back your content, i.e. accesslog, components, system configuration, and security
////

[[backup-task]]
=== Creating and Running a Database Backup Task


To create a new task for database backup:

* Go to 'Tasks' under 'System' in the 'Administration' menu.
* Choose the 'Database backup' task from the 'Select a Type' menu.
* Complete complete the form in 'Create Database backup Task'

At the top of the form the  'Task enabled' box is checked, by default, so you can run the task. Then fill
out the required fields to run the task.

* 'Task name' (required): add a name to identify your backup task
* 'Notification email': add an email to receive notification if the task fails
* 'Backup Location'(required): choose a location in your file system to store backup data
* 'Task frequency' determine and set how often you want backups to occur.

////
Expand this section, as the options (fields) for tasks registry will differ per time interval
////

After you complete the form, click 'Create task' to save your entries. The new task will be added to the 'Tasks'
screen. The screen will display 'Name', 'Type', 'Status', 'Schedule', 'Next run', 'Last run', and 'Last Result'.

////
Consider a screenshot in lieu of written description of table
////

After you fill out the form, you can run the task. Go the 'Tasks' screen start the backup:

* Click the task
* Click 'Run'
* Click 'Yes' to confirm running the task from the dialog ('Confirm?')

On the 'Tasks' screen the 'Status' column will affirm the status as 'Running'.


[[backup-node]]
=== Backing up a Single Node in {nxrm}

TBD
////
Distinguish single node backup from an backup for HA
////


[[backup-ha]]
=== Backing up {nxrm} in an HA Environment

TBD

[[backup-retrieve]]
=== Restoring a Database Backup

TBD
////
potentially, subtask for NEXUS-11203
////
