[[contrib]]
[appendix]
== Contributing to the Nexus Documentation

The Nexus documentation is an open source project in which you can participate, 
if you have an idea for documentation.  Sonatype's books include open 
writing efforts, and we see the value of the documentation contributions 
the same as code contributions.  If you are interested in our technology 
and would like to contribute, please review the basics described in Appendix A.

[[contrib-sect-cla]]
.Contributor License Agreement (CLA)

In order to contribute to the Nexus book, you will first need to fill
out a contributor license agreement. This is a legal agreement between
you and Sonatype that ensures that your contributions are not covered
by any other legal requirements. Sonatype requires contributors to
sign this agreement for all major contributions larger than
a single section. If your contribution consists of finding and fixing
simple typos or suggesting minor changes to the wording or sequence of
a particular section, you can contribute these changes via the
Sonatype support site or directly as a pull request on the github project. 
If you contribution involves direct
contribution of a number of sections or chapters you will first need
to sign our Contributor License Agreement (CLA).

To download the CLA from the following URL:
http://www.sonatype.org/SonatypeCLA.pdf

Once you have completed and signed this document, you can email the
scan to mailto:books@sonatype.com[books@sonatype.com].

.How to Contribute

The source code for the book is hosted on GitHub in the
https://github.com/sonatype/nexus-book[nexus-book]
project. Instructions on tools used to author content as well as
building the book and more can be found there.

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////
