[[backup]]
==  Backing Up and Restoring {nxrm}
{inall}

TBD

[[backup-introduction]]
=== Introduction

TBD

[[why-backup]]
=== Why Backup?

TBD

[[backup-configuration]]
=== Backup Plan

TBD
////
Checklist, self-repair tasks - TBD
////


[[backup-requirements]]
=== Requirements for Backing Up {nxrm}

TBD


[[backup-preparation]]
=== Preparing a Backup for {nxrm}

TBD
////
Formalize: Before you execute a backup of your OrientDB, select a backup tool of your preference to
back your content, i.e. accesslog, components, system configuration, and security
////

[[backup-task]]
=== Creating and Running a Database Backup Task

To create a new task for database backup:

1. Go to 'Tasks' under 'System' in the 'Administration' menu.
2. Choose the 'Database backup' task from the 'Select a Type' menu.
3. Complete the form in 'Create Database backup Task'.

At the top of the form the 'Task enabled' box is checked, by default, so you can run the task. Then fill
out the required fields to configure the task.

* 'Task name' (required): add a name to identify your backup task
* 'Notification email': add an email to receive notification if the task fails
* 'Backup location'(required): choose a location in your file system to store backup data
* 'Task frequency' (required): determine and set how often you want backups to occur.

Depending on the number of times you want the task to occur, custom fields will appear for you to set task
occurrence (e.g. calendar date, day of week, time, etc.). You can also use CRON expression to control the
occurrence of your backup tasks.

After you complete the form, click 'Create task' to save your entries. The new task will be added to the 'Tasks'
screen. The screen will display 'Name', 'Type', 'Status', 'Schedule', 'Next run', 'Last run', and 'Last Result'.

////
Consider a screenshot in lieu of written description of table
////

After you save the task, you can run the task. Go to the 'Tasks' screen to start the backup:

1. Click the task
2. Click 'Run'
3. Click 'Yes' to confirm running the task from the dialog

On the 'Tasks' screen the 'Status' column will affirm the status as 'Running'.

Running the task exports backup data to the location designated in the 'Backup location' field. The designated
location will contain +.bak+ files from the underlying databases, including:

* access log
* auditing
* component
* repository manager configuration
* security configuration

All backup files are presented in the timestamp format +dbname-YYYY-MM-DD-HH-MM-SS.bak+.


[[backup-node]]
=== Backing up a Single Node in {nxrm}

TBD
////
Distinguish single node backup from an backup for HA
////


[[backup-ha]]
=== Backing up {nxrm} in an HA Environment

TBD

[[backup-retrieve]]
=== Restoring a Database Backup

TBD
////
potentially, subtask for NEXUS-11203
////
