[[pypi]]
== PyPi Repositories
{inall}

[[pypi-introduction]]
=== Introduction

{pro} and {oss} support the PyPi repository format for hosted and proxy repositories. This allows the repository
manager to take advantage of the packages in the official PyPi repository and other public registries without
incurring repeated downloads of packages.

[[pypi-proxy]]
=== Proxying PyPi Repositories

You can set up a PyPi proxy repository to access a remote repository location, for example the official PyPi repository at https://pypi.python.org/pypi[https://pypi.python.org/pypi] that is configured as the default on PyPi.

////
[[pypi-hosted]]
=== Hosting PyPi Repositories

TBD
////

////
[[pypi-group]]
=== PyPi Repository Groups

TBD
////

////
[[pypi-installation]]
=== Installing PyPi Client Tools

TBD
////

[[pypi-browse-search]]
=== Browsing PyPi Repositories and Searching Packages

You can browse PyPi repositories in the user interface inspecting the components and assets and their details, as
described in <<search-components>>.

Searching for PyPi packages can be performed in the user interface, too. It finds all packages that are currently
stored in the repository manager, either because they have been pushed to a hosted repository or they have been
proxied from an upstream repository and cached in the repository manager.
