[[backup]]
==  Backing Up and Restoring {nxrm}
{inall}

TBD

[[backup-introduction]]
=== Introduction

TBD

[[why-backup]]
=== Why Backup?

TBD

[[backup-configuration]]
=== Backup Plan

TBD
////
Checklist, self-repair tasks - TBD
////


[[backup-requirements]]
=== Requirements for Backing Up {nxrm}

TBD


[[backup-preparation]]
=== Preparing a Backup for {nxrm}

TBD
////
Formalize: Before you execute a backup of your OrientDB, select a backup tool of your preference to
back your content, i.e. accesslog, components, system configuration, and security
////

[[backup-task]]
=== Configuring and Running a Database Backup Task

{nxrm} allows you to back up your underlying databases for both a single-node deployment or a cluster of
multiple nodes, when activating <<high-availability>>.

To configure and run a new task for database backup, review the steps in <<admin-system-tasks>>. You will
also be required to complete additional fields to configure the backup:

* 'Backup location' (required): choose a directory in your filesystem to store backup data
* 'Node performing backup' (required): select an active node to store backup data, when high availability
is enabled

////
Consider a screenshot in lieu of written description of table
////

////
expand the statement below, place it in the Preparation section
////
When the task runs it exports backup data to the location added to the 'Backup location' field. The directory
you choose will contain +.bak+ files of the following databases:

Access log:: login and usage information among repository manager users 
Analytics:: event data and overall repository manager usage
Auditing:: system feed features enabled in the repository manager
Component:: all contents of the component database
Configuration:: general adminstrative configurations such as scheduled tasks, email server configuration, etc
Security:: all user and access rights management content

All backup files are presented in the timestamp format based on the time the task was completed.

[[backup-node]]
=== Backing up a Single Node in {nxrm}

TBD
////
Distinguish single node backup from an backup for HA
////


[[backup-ha]]
=== Backing up {nxrm} in an HA Environment

TBD

[[backup-retrieve]]
=== Restoring a Database Backup

TBD
////
potentially, subtask for NEXUS-11203
////
