[[license]]
[appendix]
== Creative Commons License

This work is licensed under a Creative Commons
Attribution-Noncommercial-No Derivative Works 3.0 United States
license.  For more information about this license, see
http://creativecommons.org/licenses/by-nc-nd/3.0/us/.  You are free to
share, copy, distribute, display, and perform the work under the
following conditions:

* You must attribute the work to Sonatype, Inc. with a link to
  http://www.sonatype.com[http://www.sonatype.com].

* You may not use this work for commercial purposes.

* You may not alter, transform, or build upon this work.

If you redistribute this work on a web page, you must include the
following link with the URL in the 'about attribute' listed on a single
line (remove the backslashes and join all URL parameters):

----
<div xmlns:cc="http://creativecommons.org/ns#" 
about="http://creativecommons.org/license/results-one?q_1=2&q_1=1\
&field_commercial=n&field_derivatives=n&field_jurisdiction=us\
&field_format=StillImage&field_worktitle=Repository%3A+\Management\
&field_attribute_to_name=Sonatype%2C+Inc.\
&field_attribute_to_url=http%3A%2F%2Fwww.sonatype.com\
&field_sourceurl=http%3A%2F%2Fwww.sonatype.com%2Fbook\
&lang=en_US&language=en_US&n_questions=3">
<a rel="cc:attributionURL" property="cc:attributionName" 
href="http://www.sonatype.com">Sonatype, Inc.</a> / 
<a rel="license" 
href="http://creativecommons.org/licenses/by-nc-nd/3.0/us/">
CC BY-NC-ND 3.0</a>
</div>
----

When downloaded or distributed in a jurisdiction other than the United
States of America, this work shall be covered by the appropriate
ported version of Creative Commons Attribution-Noncommercial-No
Derivative Works 3.0 license for the specific jurisdiction. If the
Creative Commons Attribution-Noncommercial-No Derivative Works version
3.0 license is not available for a specific jurisdiction, this work
shall be covered under the Creative Commons
Attribution-Noncommercial-No Derivate Works version 2.5 license for
the jurisdiction in which the work was downloaded or distributed. A
comprehensive list of jurisdictions for which a Creative Commons
license is available can be found on the Creative Commons
International web site 
at http://creativecommons.org/international[http://creativecommons.org/international].

If no ported version of the Creative Commons license exists for a
particular jurisdiction, this work shall be covered by the generic,
unported Creative Commons Attribution-Noncommercial-No Derivative
Works version 3.0 license available from
http://creativecommons.org/licenses/by-nc-nd/3.0/[http://creativecommons.org/licenses/by-nc-nd/3.0/].

[[copyright-sect-creative-commons]]
=== Creative Commons BY-NC-ND 3.0 US License

http://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode[Creative
Commons Attribution-NonCommercial-NoDerivs 3.0 United
States]

THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS OF THIS
CREATIVE COMMONS PUBLIC LICENSE ("CCPL" OR "LICENSE"). THE WORK IS
PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. ANY USE OF THE WORK
OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR COPYRIGHT LAW IS
PROHIBITED.

BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND
AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE EXTENT THIS
LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU THE
RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS
AND CONDITIONS.

. Definitions

.. "Collective Work" means a work, such
as a periodical issue, anthology or encyclopedia, in which the
Work in its entirety in unmodified form, along with one or more
other contributions, constituting separate and independent works
in themselves, are assembled into a collective whole. A work
that constitutes a Collective Work will not be considered a
Derivative Work (as defined below) for the purposes of this
License.

.. "Derivative Work" means a work based
upon the Work or upon the Work and other pre-existing works,
such as a translation, musical arrangement, dramatization,
fictionalization, motion picture version, sound recording, art
reproduction, abridgment, condensation, or any other form in
which the Work may be recast, transformed, or adapted, except
that a work that constitutes a Collective Work will not be
considered a Derivative Work for the purpose of this License.
For the avoidance of doubt, where the Work is a musical
composition or sound recording, the synchronization of the Work
in timed-relation with a moving image ("synching") will be
considered a Derivative Work for the purpose of this
License.

.. "Licensor" means the individual,
individuals, entity or entities that offers the Work under the
terms of this License.

.. "Original Author" means the
individual, individuals, entity or entities who created the
Work.

.. "Work" means the copyrightable work
of authorship offered under the terms of this License.

.. "You" means an individual or entity
exercising rights under this License who has not previously
violated the terms of this License with respect to the Work, or
who has received express permission from the Licensor to
exercise rights under this License despite a previous
violation.

. Fair Use Rights. Nothing in this license
is intended to reduce, limit, or restrict any rights arising from
fair use, first sale or other limitations on the exclusive rights of
the copyright owner under copyright law or other applicable
laws.

. License Grant. Subject to the terms and
conditions of this License, Licensor hereby grants You a worldwide,
royalty-free, non-exclusive, perpetual (for the duration of the
applicable copyright) license to exercise the rights in the Work as
stated below:

.. to reproduce the Work, to incorporate the Work into one or
more Collective Works, and to reproduce the Work as incorporated
in the Collective Works; and,

.. to distribute copies or phonorecords of, display publicly,
perform publicly, and perform publicly by means of a digital
audio transmission the Work including as incorporated in
Collective Works.

The above rights may be exercised in all media and formats
whether now known or hereafter devised. The above rights include the
right to make such modifications as are technically necessary to
exercise the rights in other media and formats, but otherwise you
have no rights to make Derivative Works. All rights not expressly
granted by Licensor are hereby reserved, including but not limited
to the rights set forth in Sections 4(d) and 4(e).

. Restrictions.The license granted in
Section 3 above is expressly made subject to and limited by the
following restrictions:

.. You may distribute, publicly display, publicly perform, or
publicly digitally perform the Work only under the terms of this
License, and You must include a copy of, or the Uniform Resource
Identifier for, this License with every copy or phonorecord of
the Work You distribute, publicly display, publicly perform, or
publicly digitally perform. You may not offer or impose any
terms on the Work that restrict the terms of this License or the
ability of a recipient of the Work to exercise the rights
granted to that recipient under the terms of the License. You
may not sublicense the Work. You must keep intact all notices
that refer to this License and to the disclaimer of warranties.
When You distribute, publicly display, publicly perform, or
publicly digitally perform the Work, You may not impose any
technological measures on the Work that restrict the ability of
a recipient of the Work from You to exercise the rights granted
to that recipient under the terms of the License. This Section
4(a) applies to the Work as incorporated in a Collective Work,
but this does not require the Collective Work apart from the
Work itself to be made subject to the terms of this License. If
You create a Collective Work, upon notice from any Licensor You
must, to the extent practicable, remove from the Collective Work
any credit as required by Section 4(c), as requested.

.. You may not exercise any of the rights granted to You in
Section 3 above in any manner that is primarily intended for or
directed toward commercial advantage or private monetary
compensation. The exchange of the Work for other copyrighted
works by means of digital file-sharing or otherwise shall not be
considered to be intended for or directed toward commercial
advantage or private monetary compensation, provided there is no
payment of any monetary compensation in connection with the
exchange of copyrighted works.

.. If You distribute, publicly display, publicly perform, or publicly
digitally perform the Work (as defined in Section 1 above) or
Collective Works (as defined in Section 1 above), You must, unless a
request has been made pursuant to Section 4(a), keep intact all
copyright notices for the Work and provide, reasonable to the medium
or means You are utilizing: (i) the name of the Original Author (or
pseudonym, if applicable) if supplied, and/or (ii) if the Original
Author and/or Licensor designate another party or parties (e.g., a
sponsor institute, publishing entity, journal) for attribution
("Attribution Parties") in Licensor's copyright notice, terms of
service or by other reasonable means, the name of such party or
parties; the title of the Work if supplied; to the extent reasonably
practicable, the Uniform Resource Identifier, if any, that Licensor
specifies to be associated with the Work, unless such URI does not
refer to the copyright notice or licensing information for the
Work. The credit required by this Section 4(c) may be implemented in
any reasonable manner; provided, however, that in the case of a
Collective Work, at a minimum such credit will appear, if a credit for
all contributing authors of the Collective Work appears, then as part
of these credits and in a manner at least as prominent as the credits
for the other contributing authors. For the avoidance of doubt, You
may only use the credit required by this clause for the purpose of
attribution in the manner set out above and, by exercising Your rights
under this License, You may not implicitly or explicitly assert or
imply any connection with, sponsorship or endorsement by the Original
Author, Licensor and/or Attribution Parties, as appropriate, of You or
Your use of the Work, without the separate, express prior written
permission of the Original Author, Licensor and/or Attribution
Parties.

. Representations, Warranties and Disclaimer

UNLESS OTHERWISE MUTUALLY AGREED TO BY THE PARTIES IN WRITING,
LICENSOR OFFERS THE WORK AS-IS AND ONLY TO THE EXTENT OF ANY RIGHTS
HELD IN THE LICENSED WORK BY THE LICENSOR. THE LICENSOR MAKES NO
REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING THE WORK,
EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT
LIMITATION, WARRANTIES OF TITLE, MARKETABILITY, MERCHANTIBILITY,
FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, OR THE ABSENCE OF
LATENT OR OTHER DEFECTS, ACCURACY, OR THE PRESENCE OF ABSENCE OF
ERRORS, WHETHER OR NOT DISCOVERABLE. SOME JURISDICTIONS DO NOT ALLOW
THE EXCLUSION OF IMPLIED WARRANTIES, SO SUCH EXCLUSION MAY NOT APPLY
TO YOU.

. Limitation on Liability. EXCEPT TO THE EXTENT REQUIRED BY APPLICABLE
LAW, IN NO EVENT WILL LICENSOR BE LIABLE TO YOU ON ANY LEGAL THEORY
FOR ANY SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY
DAMAGES ARISING OUT OF THIS LICENSE OR THE USE OF THE WORK, EVEN IF
LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

. Termination

.. This License and the rights granted hereunder will terminate
automatically upon any breach by You of the terms of this
License. Individuals or entities who have received Collective Works
(as defined in Section 1 above) from You under this License, however,
will not have their licenses terminated provided such individuals or
entities remain in full compliance with those licenses. Sections 1, 2,
5, 6, 7, and 8 will survive any termination of this License.

.. Subject to the above terms and conditions, the license
granted here is perpetual (for the duration of the applicable
copyright in the Work). Notwithstanding the above, Licensor
reserves the right to release the Work under different license
terms or to stop distributing the Work at any time; provided,
however that any such election will not serve to withdraw this
License (or any other license that has been, or is required to
be, granted under the terms of this License), and this License
will continue in full force and effect unless terminated as
stated above.

. Miscellaneous

.. Each time You distribute or publicly digitally perform the Work (as
defined in Section 1 above) or a Collective Work (as defined in
Section 1 above), the Licensor offers to the recipient a license to
the Work on the same terms and conditions as the license granted to
You under this License.

.. If any provision of this License is invalid or
unenforceable under applicable law, it shall not affect the
validity or enforceability of the remainder of the terms of this
License, and without further action by the parties to this
agreement, such provision shall be reformed to the minimum
extent necessary to make such provision valid and
enforceable.

.. No term or provision of this License shall be deemed
waived and no breach consented to unless such waiver or consent
shall be in writing and signed by the party to be charged with
such waiver or consent.

.. This License constitutes the entire agreement between the
parties with respect to the Work licensed here. There are no
understandings, agreements or representations with respect to
the Work not specified here. Licensor shall not be bound by any
additional provisions that may appear in any communication from
You. This License may not be modified without the mutual written
agreement of the Licensor and You.

[[license-sect-ccnotice]]
=== Creative Commons Notice

Creative Commons is not a party to this License, and makes no
warranty whatsoever in connection with the Work. Creative Commons will
not be liable to You or any party on any legal theory for any damages
whatsoever, including without limitation any general, special,
incidental or consequential damages arising in connection to this
license. Notwithstanding the foregoing two (2) sentences, if Creative
Commons has expressly identified itself as the Licensor hereunder, it
shall have all rights and obligations of Licensor.

Except for the limited purpose of indicating to the public that
the Work is licensed under the CCPL, Creative Commons does not authorize
the use by either party of the trademark "Creative Commons" or any
related trademark or logo of Creative Commons without the prior written
consent of Creative Commons. Any permitted use will be in compliance
with Creative Commons' then-current trademark usage guidelines, as may
be published on its website or otherwise made available upon request
from time to time. For the avoidance of doubt, this trademark
restriction does not form part of this License.

Creative Commons may be contacted at
http://creativecommons.org/.

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////
