[[plugins]]
== Using Nexus Plugins

Nexus Open Source and Nexus Professional are built using a plugin
architecture, where Professional simply includes additional
plugins. Besides the default installed plugins you can install optional
plugins shipped with Nexus as well as plugins you or somebody else
created.
 
[[install-additional-plugins]]
=== Installing Additional Plugins


All plugins supplied by Sonatype are installed as part of the default
configuration and can be found in
+$NEXUS_HOME/nexus/WEB-INF/plugin-repository+.  Most plugins are
enabled by default. Some plugins are expose a capability as documented
in <<confignx-sect-capabilities>> and can therefore be enabled,
disabled and otherwise configured in the the capability
administration. The branding plugin or the outreach plugin are
examples of plugins exposing capabilities.

Prior to Nexus 2.7 optional plugins supplied by Sonatype can be found
in the directory +$NEXUS_HOME/nexus/WEB-INF/optional-plugins+. To
install any of these simply copy the folder containing the desired
plugin into +$NEXUS_HOME/nexus/WEB-INF/plugin-repository+.  When
updating Nexus you had to redo the install of any optinal plugins
using the newest version shipping with the download of the new Nexus
version. Any configuration of the plugin will be preserved from one
version to the other.

Plugins supplied by third parties or authored by yourself are
installed by copying the folder with the plugin code into
+sonatype-work/nexus/plugin-repository+.

After a restart of Nexus the new plugins will be active and ready
to use. Upgrades are done by simply copying over the newer plugin and
removing the older one.

Capability based plugins can be disabled in the capability
administration. Otherwise plugins can be removed by deleting the
respective folder in the plugin-repository and restarting Nexus.



////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////
