[[migration]]
==  Migration
{inall}


[[migration-introduction]]
=== Introduction

You can install {oss} on a new server or even the same server and run it in parallel. This gives you 
access to the new repository formats and features without interrupting your tested and proven {oss} 2 deployment.

////
Expand intro; Topics and headers subject to change. Note below will eventually be moved to its own section in 
configuration
////

With the migration tool you have the option to stand up a new Nexus 3 instance on the same system as Nexus 2 and 
enable it for migration. The instance won’t be available for serving content but should have some form of 
migration UI for status reporting.  You will be able to initiate a migration into Nexus 3 only once, which means 
it’s a big bang conversion. By doing this on the same system, we hope to be able to leverage Hard Links, Sym 
Links and local file copies in that preferred order. This should reduce the amount of time for a conversion quite 
significantly (in the hard/sym link scenarios) which makes a big bang more tolerable.


////
Expand intro; Topics and headers subject to change
////

[[migration-configuration]]
=== Migration Configuration

Tbd
////
This section focuses on the Migration agent - the plugin used to enable migraton. This section will cover what 
the user configures the application port as a preliminary step for the migration 
plan. This section will also provide any commandline, system

Also mention blobstore config for migration & inode
////

[[migration-options]]
=== Migration Options

TBD

////
Options include Hard Links, Sym Links and local file copies in that preferred order
////

[[migration-capabililty]]
=== Enabling the Migration Capability

To implement migration, a migration-agent capability must be activated for the migration plan to persist. The 
capability, essentially, finds what repositories exist and lists them in the version 3 migration wizard. It 
enables the port you configured to run version 2 remotely in order to communicate with version 3. The 
migration plan, as a whole, is two-part process where version 2 must be set up to listen for a {oss} 3 instance 
in order for the former to talk to the latter

[[migration-agent]]
==== Enabling Migration from Version 2

In version 2, activate the 'Migration: Agent' capability to open the connection for the migration-agent. Follow these steps:

* Click 'Administration' in the left-hand panel
* Click 'Capabilities' under 'Adminstration' to open the 'Capabilities' panel
* Select 'New' to prompt the 'Create new capability' modal
* Select 'Migration: Agent' as your capability type

In the lower section of 'Capabilities' interface, the repository manager acknowledges the migration-agent as 
'Active'. 

[[migration-nexus-three]]
==== Enabling Migration from Version 3

Next, sign in to your version 3 instance. At this point, map the <<migration-agent,migration-agent>> 
endpoint to your version 3 instance so the migration runs on the same server as version 2. Follow these 
steps to implement the migration plan:

* Click 'Capabilities', located under 'System', to open the 'Capabilities' screen
* Click 'Create capability'
* Select 'Migration', then click 'Create capability' to enable migration

[[migration-steps]]
=== Migrating Repositories

After you establish migration capabilities for versions 2 and 3, you will activate a wizard to start your 
migration. Go to the 'Adminstration' menu and select 'Migration', located under 
'System', to open the wizard.

*Migration Wizard*

Overview:: The wizard will provide and overview of what is permissible for automatic migration as well as 
warnings on what cannot be migrated. 

Agent Connection:: TBD
////
Explain what this is, the endpoint you configured from v2
////

Content:: TBD
////
Explain content items
////

Repository Defaults:: TBD
////
Destination, Method
////

Repositories:: TBD
////
select the repositories you want to migrate, NEXT
////

Preview:: TBD
////
Describe preview of the migration config; Click yes from the modal Begin Migration
////

Synchronizing:: TBD
////
Describe what this does, action taken; Finish
////

