[[contrib]]
[appendix]
== Contributing to the Nexus Book

This appendix covers the basics of contributing to the book you are
currently reading. This book is an open source project, you can
participate in the writing effort if you have an idea for
documentation. Sonatype's books are
different: they are open writing efforts and we see documentation
contributions as having equal value to code contributions.  If you are
interested in our technology, we'd welcome your contribution.

[[contrib-sect-cla]]
=== Contributor License Agreement (CLA)

In order to contribute to the Nexus book, you will first need to fill
out a contributor license agreement. This is a legal agreement between
you and Sonatype which ensures that your contributions are not covered
by any other legal requirements. Sonatype requires contributors to
sign this agreement for all major contributions which are larger than
a single section. If your contribution consists of finding and fixing
simple typos or suggesting minor changes to the wording or sequence of
a particular section, you can contribute these changes via the
Sonatype JIRA instance.  If you contribution involves direct
contribution of a number of sections or chapters you will first need
to sign our Contributor License Agreement (CLA).

To download the CLA from the following URL:
http://www.sonatype.org/SonatypeCLA.pdf

Once you have completed and signed this document, you can fax it to:
(650) 472-9197

[[contrib-sect-class]]
=== Contributors, Authors, and Editors

As with any open source effort, the contributors to the Nexus book are
grouped into a simple hierarchy. Sonatype's writing efforts are
loosely structured, but we have found it necessary to define some
formal categories for contributors.

Reviewers:: Many individuals have read the book and taken the time to
report typos and bugs. Reviewers are always credited in the Foreword
of the book and they make an important contribution to the quality of
the book.

Contributors:: Contributors are individuals who have contributed one
or more sections to the book. Many contributors make a one time
contribution to a particular section or collection of
sections. Contributors are always credited in the Foreword of the
book, and if a contributor sustains a constant level of contribution
which adds up to the equivalent of an entire chapter, a contributors
name will be added to the list of contributing authors.

Authors:: Authors have made a significant contribution to the book
equal to the equivalent of one or more chapters. A long-time
contributor can also be transitioned to the status of Author at the
discretion of an Editor. Authors are often given editorial control
over specific chapters or sections of a book, working with
Contributors to review, accept, and refine contributions to defined
sections of the book.

Editors:: An Author can also be an Editor. Each book has at least one
editor (and ideally no more than two Editors at any time). On Sonatype
Open book projects, Editors are the arbiters of content, they review
content submissions and make final decisions about content direction.

For each of these levels, the adjective "Active" can be used if a
contributor, author, or editor has been active during the previous 12
months. If you have any questions about contributor status, send any
enquiries to book@sonatype.com

=== How to Contribute

The source code for the book is hosted on GitHub in the
https://github.com/sonatype/nexus-book[nexus-book]
project. Instructions on tools used to author content as well as
building the book and more can be found there.

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////
