[[backup]]
==  Backing Up and Restoring {nxrm}
{inall}

TBD

[[backup-introduction]]
=== Introduction

TBD

[[why-backup]]
=== Why Backup?

TBD

[[backup-configuration]]
=== Backup Plan

TBD
////
Checklist, self-repair tasks - TBD
////


[[backup-requirements]]
=== Requirements for Backing Up {nxrm}

TBD


[[backup-preparation]]
=== Preparing a Backup for {nxrm}

TBD
////
Formalize: Before you execute a backup of your OrientDB, select a backup tool of your preference to
back your content, i.e. accesslog, components, system configuration, and security
////

[[backup-task]]
=== Configuring and Running a Database Backup Task

{nxrm} allows you to back up your underlying databases for both a single-node deployment or a cluster of
multiple nodes, when activating <<high-availability>>.

To configure a new task for database backup, review the steps in <<admin-system-tasks>>. You will also be
required to complete additional fields to configure the backup:

* 'Backup location' (required): choose a directory in your filesystem to store backup data
* 'Node performing backup' (required): select an active node to store backup data

////
Consider a screenshot in lieu of written description of table
////

After you save the task, you can run the task. Go to the 'Tasks' screen to start the backup:

1. Click the task
2. Click 'Run'
3. Click 'Yes' to confirm running the task from the dialog

On the 'Tasks' screen the 'Status' column will affirm the status as 'Running'.

Running the task exports backup data to the location designated in the 'Backup location' field. The designated
location will contain +.bak+ files from the underlying databases, including:

* access log
* auditing
* component
* repository manager configuration
* security configuration

All backup files are presented in the timestamp format +dbname-YYYY-MM-DD-HH-MM-SS.bak+.


[[backup-node]]
=== Backing up a Single Node in {nxrm}

TBD
////
Distinguish single node backup from an backup for HA
////


[[backup-ha]]
=== Backing up {nxrm} in an HA Environment

TBD

[[backup-retrieve]]
=== Restoring a Database Backup

TBD
////
potentially, subtask for NEXUS-11203
////
