[[pypi]]
== PyPi Repositories
{inall}

[[pypi-introduction]]
=== Introduction

{pro} and {oss} support the PyPI repository format for hosted and proxy repositories. This allows the repository
manager to take advantage of the packages in the official PyPI repository and other public registries without
incurring repeated downloads of packages.

Repository manager users will use 'virtualenv', a command line tool supported by Python. 'virtualenv' is used to 
create isolate Python environments/installations on your machine. In other words 'virualenv' solves dependency 
issues by keeping unique Python packages separate. 'virtualenv' helps you develop and test against 
different versions of the Python interpreter and different versions/combinations of installed packages without 
modifying your main Python installation.

[[pypi-proxy]]
=== Proxying PyPI Repositories

You can set up a PyPI proxy repository to access a remote repository location, for example the official PyPi repository at https://pypi.python.org/pypi[https://pypi.python.org/pypi] that is configured as the default on PyPi.

////
[[pypi-hosted]]
=== Hosting PyPI Repositories

////

////

[[pypi-group]]
=== PyPI Repository Groups

TBD
////

////
[[pypi-installation]]
=== Installing PyPI Client Tools

TBD
////

[[pypi-browse-search]]
=== Browsing PyPI Repositories and Searching Packages

You can browse PyPI repositories in the user interface inspecting the components and assets and their details, as
described in <<search-components>>.

Searching for PyPI packages can be performed in the user interface, too. It finds all packages that are currently
stored in the repository manager, either because they have been pushed to a hosted repository or they have been
proxied from an upstream repository and cached in the repository manager.
