[[community]]
==  Community

{inall}

[[community-introduction]]
=== Introduction

{oss} and {pro} are widely used in a large variety of organizations for numerous different use cases.

Integrating the repository manager and expanding its features is encouraged and enabled by the availability of
{oss} under the Eclipse Public License, <<confignx-sect-plugins, the REST API>> and <<plugdev, the support for
plugins>> as part of the repository manager itself, including writing your own plugins.

A number of tools are available to facilitate the community of users.

TheNexus:: A community website with numerous resources including blog posts, videos, announcements and many others
available at http://nexus.sonatype.org[http://nexus.sonatype.org].

Users Mailing List:: General discussion and support for anyone using and developing with {pro} or {oss} -
link:https://groups.google.com/a/glists.sonatype.com/forum/#!forum/nexus-users[Browse or Subscribe].

Chat:: Sonatype provides https://links.sonatype.com/products/nexus/community-chat[a live chat channel] to connect
to other users and developers as well as Sonatype support and development staff.

Source Code:: The {oss} codebase is a great reference for your development of custom integrations and plugins. It
is available on GitHub at https://github.com/sonatype/nexus-public/tree/nexus-2.x/[https://github.com/sonatype/nexus-public/tree/nexus-2.x/].

[[community-overview]]
=== Community Overview

Community projects range from open source efforts run by Sonatype, projects run by {pro} customers or {oss} users
to one man, one-off hacks for some older version.

When using any of these projects, ensure you keep the quality of the project and their impacts on your production
repository manager in mind.

[[community-plugins]]
=== Plugins

Plugins expand functionality of the repository manager itself in various aspects on the user interface and
underlying features:

{oss} Plugins https://github.com/sonatype/nexus-public/tree/nexus-2.x/plugins[https://github.com/sonatype/nexus-public/tree/nexus-2.x/plugins]::
Large number of plugins bundled with {oss} including YUM
support, P2 support and others.

Example Plugins https://github.com/sonatype/nexus-example-plugins[https://github.com/sonatype/nexus-example-plugins]::
Example plugins from Sonatype.

APT Plugin https://github.com/Tangresh/nexus-apt-plugin[https://github.com/Tangresh/nexus-apt-plugin]::
APT/DEB repository support.

Rundeck Plugin https://github.com/rundeck/nexus-rundeck-plugin[https://github.com/rundeck/nexus-rundeck-plugin]::
Integration with http://rundeck.org/[Rundeck]

Webhook Plugin https://github.com/vbehar/nexus-webhook-plugin[https://github.com/vbehar/nexus-webhook-plugin]::
Support for webhook notifications for component deployments.

Artifact Usage Plugin https://github.com/saleemshafi/nexus-artifact-usage-plugin[https://github.com/saleemshafi/nexus-artifact-usage-plugin]::
Plugin to display components depending on a specific component.

Dependency Mgt. Plugin https://github.com/Terracotta-OSS/nexus-dependency-management-plugin[https://github.com/Terracotta-OSS/nexus-dependency-management-plugin]::
Plugin to display the dependency tree of a component with further detailed information.

GroupId Mgt. Plugin https://github.com/UW-Madison-DoIT/nexus-groupid-management-plugin[https://github.com/UW-Madison-DoIT/nexus-groupid-management-plugin]::
Plugin to help with provisioning security per groupId.

Repository Cleanup Plugin https://github.com/Vlatombe/nexus-repository-cleanup-plugin/[https://github.com/Vlatombe/nexus-repository-cleanup-plugin/]::
Scheduled task that can remove components based on age and a regular
expression pattern.

Gitlab Token Auth Plugin https://github.com/jdamick/nexus-gitlab-token-auth-plugin[https://github.com/jdamick/nexus-gitlab-token-auth-plugin]::
Authentication support using http://gitlab.org/[Gitlab] user
token.

AWS S3 Publish Plugin https://github.com/carrot-garden/carrot-nexus[https://github.com/carrot-garden/carrot-nexus]::
lugin to publish components deployed to the repository manager also to AWS S3.

Hipchat for Nexus Plugin https://bitbucket.org/tpettersen/hipchat-for-nexus[https://bitbucket.org/tpettersen/hipchat-for-nexus]::
Supports notifications in HipChat when components matching a pattern 
are deployed to the repository manager.

[[community-integrations]]
=== Integrations

Nexus Maven Plugins https://github.com/sonatype/nexus-maven-plugins[https://github.com/sonatype/nexus-maven-plugins]::
The official Nexus Staging Maven Plugin and the Nexus M2Settings Maven Plugin from Sonatype. The plugins are using
the REST API client library and can be used as example for your own Maven plugins or other Java based clients.

Nexus Ant Tasks https://github.com/sonatype/nexus-ant-tasks[https://github.com/sonatype/nexus-ant-tasks]:: The
official Nexus Staging Ant Tasks from Sonatype.

Puppet Module for Nexus https://github.com/hubspotdevops/puppet-nexus[https://github.com/hubspotdevops/puppet-nexus]::
Puppet module to install and configure {oss}, authored by HubSpot

Puppet Module for Nexus https://forge.puppetlabs.com/atlassian/nexus_rest[https://forge.puppetlabs.com/atlassian/nexus_rest]::
Another Puppet module to manage a {nxrm}, authored by Atlassian

Nexus Cookbook https://github.com/RiotGames/nexus-cookbook[https://github.com/RiotGames/nexus-cookbook]::
 Chef cookbook to install and configure {nxrm}.

Openshift Nexus https://github.com/hongun/openshift-nexus[https://github.com/hongun/openshift-nexus]::
Scripts to provision {nxrm} on https://www.openshift.com/[OpenShift].

Nexus Ruby CLI https://github.com/RiotGames/nexus_cli[https://github.com/RiotGames/nexus_cli]::
Ruby-based set of command line programs to interact with {nxrm}.

Nexus Python CLI https://github.com/stardust85/repositorytools/[https://github.com/stardust85/repositorytools/]::
Python-based set of command line programs to interact with {nxrm}.

Nexus RPM Package https://github.com/jbraeuer/nexus-oss-rpms[https://github.com/jbraeuer/nexus-oss-rpms]::
{oss} as RPM package.

Nexus DEB Package https://github.com/tobrien/nexus-oss-deb[https://github.com/tobrien/nexus-oss-deb]::
{oss} as DEB package.

Puppet Nexus Client https://github.com/cescoffier/puppet-nexus[https://github.com/cescoffier/puppet-nexus]::
Puppet module to retrieve components from a .

Gradle Plugin https://github.com/bmuschko/gradle-nexus-plugin[https://github.com/bmuschko/gradle-nexus-plugin]::
Gradle plugin to deploy components to {nxrm} and via OSSRH to the Central Repository.

Gradle Staging Plugin https://github.com/adaptivecomputing/plugins-gradle/tree/master/nexus-workflow[https://github.com/adaptivecomputing/plugins-gradle/tree/master/nexus-workflow]::
Gradle plugin to deploy components to {pro} and via OSSRH to the Central Repository with good support for staging
automation.

SBT Plugin https://github.com/xerial/sbt-sonatype[https://github.com/xerial/sbt-sonatype]: SBT plugin to
deploy components to {pro} and via OSSRH to the Central Repository.

List Versions Jenkins Plugin https://github.com/USGS-CIDA/list-nexus-versions-plugin[https://github.com/USGS-CIDA/list-nexus-versions-plugin]::
Jenkins plugin to display available component versions.

Nexus Metadata Jenkins Plugin https://github.com/marcelbirkner/nexus-metadata-plugin[https://github.com/marcelbirkner/nexus-metadata-plugin]::
Jenkins plugin to add custom metadata with deployments to {pro}.

Artifact Promotion Jenkins Plugin https://github.com/jenkinsci/artifact-promotion-plugin[https://github.com/jenkinsci/artifact-promotion-plugin]::
Jenkins plugin allowing you to promote components to different repositories in {oss}

Go Maven Poller https://github.com/ThoughtWorksInc/go-maven-poller[https://github.com/ThoughtWorksInc/go-maven-poller]::
Package material plugin for
http://www.thoughtworks.com/products/go-continuous-delivery[Go] that can poll a {nxrm} repository for components.

Nexus Docker Image https://registry.hub.docker.com/u/conceptnotfound/sonatype-nexus/[https://registry.hub.docker.com/u/conceptnotfound/sonatype-nexus/]::
Simple Docker image including {oss}.

Nexus NPM Docker Image https://github.com/marcellodesales/nexus-npm-registry-docker-image[https://github.com/marcellodesales/nexus-npm-registry-docker-image]::
Docker Image of {oss} with NPM support preconfigured

[[community-projects]]
=== Other Community Projects

Nexus Performance Testing Library https://github.com/sonatype/nexus-perf[https://github.com/sonatype/nexus-perf]::
Regression and stress test library for {oss} from Sonatype.

Repository Management With Nexus https://github.com/sonatype/nexus-book[https://github.com/sonatype/nexus-book]::
The source code for the book, which is the official documentation for {oss} and {pro}.

Nexus Book Examples https://github.com/sonatype/nexus-book-examples[https://github.com/sonatype/nexus-book-examples]::
Examples for the trial guide chapter of the book 'Repository Management with Nexus'.

Nexus Introduction https://github.com/sonatype/nexus-introduction-presentation[https://github.com/sonatype/nexus-introduction-presentation]::
Slides and examples to present about {pro} and {oss} at user groups or in similar settings.

[[community-contributing]]
=== Contributing

All of the projects listed in <<community-projects>> are community efforts and open to your participation. If you
are aware of any other projects or would like to have your project listed here, please contact us at
mailto:books@sonatype.com[books@sonatype.com].


