[[preface]]
== Preface

[[preface-introduction]]
=== Introduction

This book covers the concepts of repository management, software supply chain management and component management
in general and specifically the usage of {pro} and {oss}. It details all aspects of set-up and running the
repository manager. Specifically this documentation of the covers version {version}.

This documentation was last updated and published on {localdate}.

[[howtoread]]
=== How to Use this Documentation

.Formats

This {pro} documentation is available online in HTML format, so you can read is in web browser, while using the
repository manager or referring other users to specific content.

The navigation bar on the left-hand side of the documentation allows you to access documentation for different
versions of {pro} as well as a number of other resources.

The top right-hand side of the documentation features a search input box that accesses all content to provide you
with the relevant information for your search term.

In addition to this online version the documetation can be downloaded in Portable Document Format (PDF) and
Electronic Publication (EPUB) format for offline access.

.{pro} Editions

The documentation covers all editions of the repository manager - {oss} and {pro}. Each chapter or smaller section
title in the documentation is followed by a text, showing in which edition the specific features are available
e.g.:

{inall}

If you can not find any specific mentions of a specific edition, it is safe to assume that the feature can be
found in all editions. Keep in mind that {pro} is an extension of {oss}.

.Conventions Used in the Documentation

A number of convetions are used through out the documentation to simplify following the instructions and content.

A user interface label or button is highlighted. E.g. use the 'Applications' button to access the list of
applications.

A code segment or command line like +mvn clean install+ input in a paragraph uses monospace fonts just like they
would be used in a command line window.

Larger code segments use the same monospace fonts and are encapsulated in a block:

----
$ mvn --version
Apache Maven 3.3.3 (79941207757...; 2015-04-22T06:57:37-05:00)
Maven home: /opt/apache-maven-3.3.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
----

The documentation uses specific blocks for notes, tips and important messages:

NOTE: You can download Java from the Oracle website.

TIP: The repository manager should be set up to run as a service.

IMPORTANT: {pro} requires Java 8.

In addition there are blocks for warnings and cautioning alerts:

WARNING: Mounting the storage directory via NFS can have negative performance and stability effects.

CAUTION: Be sure to perform a complete backup before upgrading the repository manager.

Application screenshots and other images are typically included as numbered figures and referenced from the
flowing text.

.Next Steps 

With all this in mind you can learn more about the <<concepts, concepts>> used or learn more about
<<install,installing>>, <<admin, configuring>> or <<using, using>> the repository manager or choose to read a
section about your specific use case or question.

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////
