[[contrib]]
[appendix]
== Contributing to the Nexus Book

This appendix covers the basics of contributing to the book you are
currently reading. This book is an open source project, you can
participate in the writing effort if you have an idea for
documentation. Sonatype's books are
different: they are open writing efforts and we see documentation
contributions as having equal value to code contributions.  If you are
interested in our technology, we'd welcome your contribution.

[[contrib-sect-cla]]
=== Contributor License Agreement (CLA)

In order to contribute to the Nexus book, you will first need to fill
out a contributor license agreement. This is a legal agreement between
you and Sonatype which ensures that your contributions are not covered
by any other legal requirements. Sonatype requires contributors to
sign this agreement for all major contributions which are larger than
a single section. If your contribution consists of finding and fixing
simple typos or suggesting minor changes to the wording or sequence of
a particular section, you can contribute these changes via the
Sonatype JIRA instance.  If you contribution involves direct
contribution of a number of sections or chapters you will first need
to sign our Contributor License Agreement (CLA).

To download the CLA from the following URL:
http://www.sonatype.org/SonatypeCLA.pdf

Once you have completed and signed this document, you can fax it to:
(650) 472-9197

[[contrib-sect-class]]
=== Contributors, Authors, and Editors

As with any open source effort, the contributors to the Nexus book are
grouped into a simple hierarchy. Sonatype's writing efforts are
loosely structured, but we have found it necessary to define some
formal categories for contributors.

Reviewers:: Many individuals have read the book and taken the time to
report typos and bugs. Reviewers are always credited in the Foreword
of the book and they make an important contribution to the quality of
the book.

Contributors:: Contributors are individuals who have contributed one
or more sections to the book. Many contributors make a one time
contribution to a particular section or collection of
sections. Contributors are always credited in the Foreword of the
book, and if a contributor sustains a constant level of contribution
which adds up to the equivalent of an entire chapter, a contributors
name will be added to the list of contributing authors.

Authors:: Authors have made a significant contribution to the book
equal to the equivalent of one or more chapters. A long-time
contributor can also be transitioned to the status of Author at the
discretion of an Editor. Authors are often given editorial control
over specific chapters or sections of a book, working with
Contributors to review, accept, and refine contributions to defined
sections of the book.

Editors:: An Author can also be an Editor. Each book has at least one
editor (and ideally no more than two Editors at any time). On Sonatype
Open book projects, Editors are the arbiters of content, they review
content submissions and make final decisions about content direction.

For each of these levels, the adjective "Active" can be used if a
contributor, author, or editor has been active during the previous 12
months. If you have any questions about contributor status, send any
enquiries to book@sonatype.com

[[contrib-sect-tools]]
=== Tools Used to Build and Write this Book

The following tools are used to write this book. If you are
interested in contributing to this book, you will need to download the
following software:

Asciidoc:: A very lightweight markup format with a strong community
and a collection of solid tools. For more information, see
http://www.methods.co.nz/asciidoc/

A Text Editor:: Emacs, vi, TextMate, Notepad - it doesn't matter.  All
you need to contribute to this book is a text editor.

Git:: Sonatype stores the source code for all books in GitHub so you
will need to download Git. In addition to downloading Git, if you need
read/write access to the repository you will also need to sign up for
an account on GitHub - http://www.github.com
+
Download the latest version of Git from http://git-scm.com/
+
This next set of tools are optional, and are only required if you are
involved in generating diagrams or formatting the final PDF for the
pre-print production process. In short, there is only one or two
people who will need to have access to the following set of tools,
and, in a normal publishing house, all of these functions would likely
be performed by a separate "Production" team.

Omnigraffle:: Many of the diagrams in this book have been generated
using a OSX-specific tool named Omnigraffle.
+
If you are interested in helping us create diagrams don't feel
compelled to purchase a copy of Omnigraffle. Send us a rough outline
of your diagram, and Sonatype will gladly transform your idea into a
diagram if your contributions are accepted into the book.

Adobe Photoshop:: All of the screen shots are generated using simple
screen capture tools. The resulting raw images (PNGs) are then
processed using a set of very simple Photoshop macros. These macros
add a border to each screen shot and apply a standard drop
shadow. Once the drop shadow has been applied, these macros then save
a 72 dpi PNG image for the HTML version of the book in addition to a
150 dpi PDF image for the printed version of the book,
+
While Adobe Photoshop is a capable (and somewhat formidable) graphics
manipulation tool, Sonatype is exploring alternatives to using this
commercial utility in the content generation process.  Alternatives
currently being investigated are open source packages such as GIMP or
systems which can rely on ImageMagick for scripted conversion of raw
screen shots to multiple web and print image formats.
+
If you are interested in contributing, but you do not want to bother
with the process of formatting images for both web and print, Sonatype
welcomes contributions which include raw screen captures. We can take
care of the formatting.

Adobe Illustrator:: The book cover, the promotional material insert,
and the print binder for Lulu are all generated with Adobe
Illustrator. Adobe Illustrator can open and edit PDFs natively, and
can be used to generate the static PDFs which are concatenated
together to produce the final book output.

[[contrib-sect-how]]
=== How to Build the Book

You know what, this book doesn't really have a "build" as much as it
has a collection of light-weight bash scripts which are used to invoke
Asciidoc and a2x.  If you are interested in building the book, we've
had good success on Mac OSX and Ubuntu.  Any other operation system
and you are on your own.

* Clone the book's Git repository. To clone this book's repository
execute the following command at a command-line:

----
$ git clone git@github.com:sonatype/nexus-book.git
...a bunch of Git output...
----

Running this command will create a sub-directory named nexus-book which
is a copy of this book's source.

* ./build.sh

This will create a single-page HTML version, a chunked HTML version,
and a PDF version of the book.

[[contrib-sect-subscribe]]
=== Subscribing to the Book Developers List

Sonatype maintains a Book Developers mailing list as a single mailing
list for contributors, authors, and editors working on any of our
Sonatype Open Books. This is a high volume list which contains both
discussion and automated emails from GitHub and our Sonatype Matrix
continuous integration server.

To subscribe to this mailing list, send and email to:
mailto:book-dev-subscribe@sonatype.org[book-dev-subscribe@sonatype.org]

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////
