[[integration]]
== Integrating Nexus with Other Tools

[[integration-intro]]
=== Introduction

Nexus is a component storage - and can provide the components for
downstream tools. Often they are build tools as documented in chapter
x and y but in many cases other tools like provisioning tools or
custom scripts need to work with Nexus since it is an ideal storage of
the components... blabla

nexus is very open to integration .. all repos are accessible via
plain http provided the access rights are ok and it provdes a rich
rest api for further complicated stuff

[[integration-rest]]
=== REST API 

whole ui is using rest, use firebug to check out what is going on

link to Plugin console in configuration chapter

[[integration-scripts]]
=== Integration with Shell Scripts

bash and friends... use the rest api via curl or wget

[[integration-puppet]]
=== Puppet

puppet is... 

[[integration-chef]]
=== Chef

chef is ...



////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////
