= Sonatype Nexus Professional Evaluation Guide
:data-uri:
:icons:
:docinfo:

[preface]
== Background

So you’ve downloaded Sonatype Nexus, what is this thing? How do I
evaluate a repository manager? How can I understand how the features
of Nexus map to my organization’s needs?

This guide helps you with this task, answers these question and other
questions and give you pointers to further resources and next steps.

It is based on evaluatinbg Sonatype Nexus Professional 2.3 by
providing a number of step by step instructions for typical use
cases. Some of these can be used for Sonatype Nexus Open Source as
well.

include::chapter-eval.asciidoc[]

[colophon]
== Epilogue

*Sonatype Company Overview*

Sonatype is leading the component revolution. Sonatype operates the
Central Repository, the industry’s pri- mary source for open-source
components, housing more than 300,000 components and serving more than
five billion requests per year from more than 60,000
organizations. For more information about Sonatype, go to
http://www.sonatype.com/.

*Nexus Professional Manages the Central Repository*

Founded in 2008, Sonatype is the steward of the Central Repository:
supporting millions of Java developers, serving more than 300,000
components, and designed to support over 4 billion requests per year,
making it one of the most widely accessed services on the web. If you
use a build tool today, any of them, you are already benefiting from
our dedication to supporting the world’s developers with this free
resource.

The Central Repository and the majority of OSS projects that feed this
global resource are managed using Nexus Professional.

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////

