= Sonatype Nexus Professional Evaluation Guide
:data-uri:
:icons:
:docinfo:

[[preface]]
== Prologue

This guide helps you with evaluating Sonatype Nexus Professional 2.3. 

include::chapter-eval.asciidoc[]


== Epilogue

*Sonatype Company Overview*

Sonatype is leading the component revolution. Sonatype operates the Central Repository, the industry’s pri- mary source for open-source components, housing more than 300,000 components and serving more than five billion requests per year from more than 60,000 organizations. For more information about Sonatype, go to http://www.sonatype.com/.

*Nexus Professional Manages the Central Repository*

Founded in 2008, Sonatype is the steward of the Central Repository: supporting millions of Java developers, serving more than 300,000 components, and designed to support over 4 billion requests per year, making it one of the most widely accessed services on the web. If you use a build tool today, any of them, you are already benefiting from our dedication to supporting the world’s developers with this free resource.

The Central Repository and the majority of OSS projects that feed this global resource are managed using Nexus Professional.

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////

