= Nexus Repository Manager Documentation
:data-uri:
:toc!:

include::nexus-book-declarations.asciidoc[]

The documentation for {pro} and {oss} from Sonatype is written and maintained to match the latest
available, stable releases:

* link:./reference/index.html[{nxrm} 3.0]
* link:./reference/index.html[{nxrm} 2.13]

Additionally the documentation for some older releases is available here for your convenience.

Please use the links on the navigation menu to access other resources related to the {nxrm} and the {iq} and
related suite of tools.

If you need any further assistance, please don't hesitate to consult
https://support.sonatype.com/home[https://support.sonatype.com/home] or contact us at
mailto:support@sonatype.com[support@sonatype.com].

Thanks and we look forward to your feedback,

The {nxrm} Team

== Archives

As mentioned previously, our documentation is kept in sync with the latest available version of the {nxrm}. The
following table displays all available versions and formats of the documentation, in case you need access to older
versions.

[[nexus-doc-versions]]
.Nexus Documentation Versions
[frame="topbot",options="heade"]
|==========================
| Nexus Version | HTML | PDF | EPUB 
| 3.0      | link:./3.0/reference/index.html[View]  | link:./3.0/pdf/nxbook-pdf.pdf[Download]  | link:./3.0/other/nexus-book.epub[Download]
| 2.13     | link:./2.13/reference/index.html[View] | link:./2.13/pdf/nxbook-pdf.pdf[Download] | link:./2.13/other/nexus-book.epub[Download]
| 2.12     | link:./2.12/reference/index.html[View] | link:./2.12/pdf/nxbook-pdf.pdf[Download] | link:./2.12/other/nexus-book.epub[Download]
| 2.11     | link:./2.11/reference/index.html[View] | link:./2.11/pdf/nxbook-pdf.pdf[Download] | link:./2.11/other/nexus-book.epub[Download]
| 2.10     | link:./2.10/reference/index.html[View] | link:./2.10/pdf/nxbook-pdf.pdf[Download] | link:./2.10/other/nexus-book.epub[Download]
| 2.9      | link:./2.9/reference/index.html[View]  | link:./2.9/pdf/nxbook-pdf.pdf[Download]  | link:./2.9/other/nexus-book.epub[Download]
| 2.8      | link:./2.8/reference/index.html[View]  | link:./2.8/pdf/nxbook-pdf.pdf[Download]  |
|==========================

Even older versions are only available in the https://github.com/sonatype/nexus-book[documentation source code
repository] and require you to build the desired outputs from source.

