= Documentation Index
:data-uri:
:toc!:

The documentation for Sonatype Nexus is written and maintained to match the
latest available, stable release:

link:./reference/index.html[Sonatype Nexus 2.11 - go there now...]

If you feel curious about whats next, you might want to check out
https://support.sonatype.com/forums/23079216-Nexus-3-Milestone-Releases[Nexus
3.0 preview releases] and the related
link:./3.0/reference/index.html[documentation], which we are constantly
improving as well.

Additionally we make the documentation for older releases available
here for your convenience.

Please use the links on the navigation menu to access other resources
related to Sonatype Nexus and Sonatype CLM.

If you need any further assistance, please don't hesitate to consult
https://support.sonatype.com/home[https://support.sonatype.com/home]
or contact us at mailto:support@sonatype.com[support@sonatype.com].

Thanks and we look forward to your feedback,

The Sonatype Nexus Team

== Archives

As mentioned previously, our documentation is kept in sync with the
latest available version of Sonatype Nexus. The following
table displays all available versions and formats of the
documentation, in case you need access to older versions.

[[nexus-doc-versions]]
.Nexus Documentation Versions
[frame="topbot",options="heade"]
|==========================
| Nexus Version | HTML | PDF | EPUB 
| 3.0 Preview      | link:./3.0/reference/index.html[View]  | link:./3.0/pdf/nxbook-pdf.pdf[Download] | link:./3.0/other/nexus-book.epub[Download] 
| 2.11      | link:./2.11/reference/index.html[View]  | link:./2.11/pdf/nxbook-pdf.pdf[Download] | link:./2.11/other/nexus-book.epub[Download] 
| 2.10      | link:./2.10/reference/index.html[View]  | link:./2.10/pdf/nxbook-pdf.pdf[Download] | link:./2.10/other/nexus-book.epub[Download] 
| 2.9      | link:./2.9/reference/index.html[View]  | link:./2.9/pdf/nxbook-pdf.pdf[Download] | link:./2.9/other/nexus-book.epub[Download] 
| 2.8      | link:./2.8/reference/index.html[View]  | link:./2.8/pdf/nxbook-pdf.pdf[Download] |  
|==========================

Even older versions are only available in the
https://github.com/sonatype/nexus-book[documentation source code
repository] and require you to build the desired outputs from source.

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////
