= Sonatype Nexus Evaluation Guide
:data-uri:
:icons:
:docinfo:

[preface]
== Background

So you’ve downloaded Sonatype Nexus - great! But what is a repository
manager? How do you evaluate a repository manager? How can you understand
how the features of Nexus map to your organization’s needs?

This guide helps you with this task, answers these and other questions
and gives you pointers to further resources and next steps.

It is based on evaluating Sonatype Nexus Pro and provides a
number of step by step instructions for typical use cases. Some of
these can be used for Sonatype Nexus OSS as well.

include::chapter-eval.asciidoc[]

[colophon]
== Epilogue

*Sonatype Company Overview*

Founded in 2008, Sonatype is leading the component
revolution. Sonatype operates the http://search.maven.org[Central
Repository], the industry’s primary source for open-source components,
housing more than 300,000 components and serving more than five
billion requests per year from more than 60,000 organizations. For
more information about Sonatype, go to http://www.sonatype.com/.

*Nexus Pro Manages the Central Repository*

The Central Repository is one of the most widely accessed services on
the web. If you use a build tool today like Apache Maven or one of the
many others, you are already benefiting from our dedication to
supporting the world’s developers with this free resource.

The Central Repository and the majority of OSS projects that feed this
global resource are managed using Nexus Pro and together
Nexus OSS and Nexus Pro are the most popular
repository management solution for Maven and other repositories.

////
/* Local Variables: */
/* ispell-personal-dictionary: "ispell.dict" */
/* End:             */
////

